@PORT=5003
### GET all transactions

GET http://localhost:{{PORT}}/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

### GET a transaction by id

GET http://localhost:{{PORT}}/transactions/97f77f85-c7b2-4164-807c-5951941de011 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>


### Create a new transaction
POST http://localhost:{{PORT}}/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
  "title": "New Transaction 2",
  "description": "This is a new new new transaction",
  "amount": 300.00,
  "date": "2023-10-01T12:00:00Z",
  "category": "Food",
  "type": "expense"
}

### Delete a transaction by id
DELETE http://localhost:{{PORT}}/transactions/2 HTTP/1.1
Authorization: Bearer <jwt token>

### Update a transaction by id
PUT http://localhost:{{PORT}}/transactions/97f77f85-c7b2-4164-807c-5951941de011 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
  "amount": 15.00
}

### GET all categories
GET http://localhost:{{PORT}}/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

### GET a category by id
GET http://localhost:{{PORT}}/categories/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

### Create a new category
POST http://localhost:{{PORT}}/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
  "name": "New Category",
  "type": "expense"
}
### Update a category by id
PUT http://localhost:{{PORT}}/categories/4eb2d160-61d8-4798-81ff-f0ed0c62a9c0 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
  "name": "Updated Category",
  "type": "income"
}
### Delete a category by id
DELETE http://localhost:{{PORT}}/categories/1 HTTP/1.1
Authorization: Bearer <jwt token>

### Create a new user
POST http://localhost:{{PORT}}/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "newuser",
  "email": "newuser@example.com",
  "password": "securepassword"
}

### User login
POST http://localhost:{{PORT}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "securepassword"
}